displayName: bundled skill
schemaName: Default_draft_ef3Vqn
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  recognizer:
    kind: CLICopilotRecognizer

  agentSettings:
    model:
      series: GPT53Chat

    instructions: {}

publishedOn: 2026-06-05T20:57:24.0000000Z
template: cliagent-1.0.0
language: 1033