connectionReferences:
  - connectionReferenceLogicalName: Default_InventoryFullfilmentAgent_X-w2GP.cr.shared_new-5fwarehou.89650fa4b3604076a2e730bec67b7f07
    connectorId: /providers/Microsoft.PowerApps/apis/shared_new-5fwarehouse-20mcp-5fee08b8354fad177a
