connectionReferences:
  - connectionReferenceLogicalName: Default_draft_IsBewO.cr.shared_membership-20.9567a2288d83498eb9f0305b20030ce3
    connectorId: /providers/Microsoft.PowerApps/apis/shared_membership-20mcp-5fee08b8354fad177a-5f8dc9e3504a9e5333
