connectionReferences:
  - connectionReferenceLogicalName: Default_draft_IsBewO.cr.shared_membership-20.cd48113e28c44025952903ba1e42cd0b
    connectorId: /providers/Microsoft.PowerApps/apis/shared_membership-20mcp-20v2-5fee08b8354fad177a-5f8dc9e3504a9e5333
