connectionReferences:
  - connectionReferenceLogicalName: Default_SalesPerformanceAgent_DC0HEJ.shared_new-5fsales-20and-20performance-20mcp-5fee08b8354fad177a.d4ce638fbafc458f98f5ebbd89f2a12e
    connectorId: /providers/Microsoft.PowerApps/apis/shared_new-5fsales-20and-20performance-20mcp-5fee08b8354fad177a
